### ISSUE TITLE
Scope?

### ISSUE THREAD

**Issue by brettz9** [WebReflection/query-result#1]
Not sure of your project's scope, but maybe this could provide a little inspiration for further development?

https://gist.github.com/brettz9/4009884

**Comment by WebReflection** [comment]
interesting but very "quirky" ... noSuchMetod doen't feel the right way to go to me, although I made this very easy to extend so you can add even noSuchMethod if you like ;-)

**Comment by brettz9** [comment]
It was on my todos to replace it with the equivalent for Proxy...and what do you think of DOM creation (and DOMContentLoaded)?

**Comment by brettz9** [comment]
(And not talking about my implementation btw, as it is just a sketch--just the ideas)

**Comment by WebReflection** [comment]
Not a big fun of strings passed to build things. I'd go templates at that
point. More powerful than just that.
