### ISSUE TITLE
Access from within extensions to query-result `$` factory

### ISSUE THREAD

**Issue by brettz9** [WebReflection/query-result#5]
Is there any chance you may expose `$` to extensions (e.g., passing as an argument to `$.extend`)? There is access from within extensions to `this.constructor`, but that misses out on the logic of `$` (and `search`)...

I came across this concern in developing a module to mimic jQuery's `appendTo` and other such functions which accept selectors, and I think it makes sense for those selectors to have the same syntax as `$`, e.g., to allow for `:first`.

I could add a mutual dependency with query-result to offer this, but this seems wasteful (if not potentially incompatible if you ever use `instanceof` or such).

**Comment by WebReflection** [comment]
not sure I understand what you are asking ... I usually understand easily by code examples though, any chance you can write what you need or where/why/how?

**Comment by brettz9** [comment]
```js
$.extend('appendTo', function (target) {
    target = Array.isArray(target) ? target : [target];
    target.forEach((t, i, arr) => {
      if (typeof t === 'string' && t.charAt(0) !== '<') { // Assume this is a selector
        t = $(t); // How do I get a copy of `$` that I can use in this plugin to ensure I'm using the same syntax of query-selector, but without the bloat/risks of duplicating code?
      }
      const avoidCloning = i === arr.length - 1; // Clone all but the last one (like jQuery)
      t = convertToDOM(t, avoidCloning);
      t.append(...this);
    });
    return this;
  }
});
```

**Comment by WebReflection** [comment]
I am still not following, sorry ... so, you define through `$.extend` and you expect that `$` is something else inside the very same definition? For what I can tell, you have `$` already in the outer scope, not sure why you need anything else than `$(t)` in there.

Or maybe I don't understand at all what you are doing ... and I'm also not sure what `this` you expect in that arrow. Do you have any jQuery live example that shows what you are trying to do?

**Comment by WebReflection** [comment]
> I'm also not sure what this you expect in that arrow.

meaning, I don't understand why would you **ever** pass `...this` to an append, since nodes are obviously not cloned per spread operation, so you are going to re-append every single time the initial found collection per each item in that `forEach` ... sorry but I don't really understand what are you trying to do.

**Comment by WebReflection** [comment]
maybe I got it ...
```js
$.extend('clone', function (deep) {
  return this.map(node => node.cloneNode(deep));
});
$.extend('appendTo', function (target) {
  const result = $(target);
  result.forEach((node, i, all) => {
      node.append(...(i === (all.length - 1) ? this : this.clone(true));
      return true;
  });
  return result;
});
```

anyway, if you are rewriting jQuery, I think you should just use jQuery and stop bothering with this library which is meant to keep it simple.
